import './globals.css'
import {Inter} from 'next/font/google'
import clsx from "clsx";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body
            className={clsx(inter.className, "bg-slate-200 dark:bg-slate-800 container m-auto grid items-center justify-center py-8 w-full min-w-[300px] min-h-screen")}>{children}</body>
        </html>
    )
}
