# Generated by Django 4.2.1 on 2023-05-28 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieWebsite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="director",
            name="person_ptr",
        ),
        migrations.RemoveField(
            model_name="person",
            name="movies",
        ),
        migrations.RemoveField(
            model_name="writer",
            name="person_ptr",
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Director",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Writer",
        ),
    ]
