# Generated by Django 4.2.1 on 2023-05-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movieWebsite",
            "0002_remove_director_person_ptr_remove_person_movies_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "bio",
                    models.TextField(
                        help_text="Enter a brief description of the actor."
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(help_text="Enter the year the actor was born."),
                ),
                (
                    "movies",
                    models.ManyToManyField(
                        help_text="The movies the actor has acted in.",
                        related_name="actors",
                        to="movieWebsite.movie",
                    ),
                ),
            ],
        ),
    ]
