# Generated by Django 4.2.1 on 2023-05-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieWebsite", "0003_actor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="movies",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True,
                help_text="The actors in the movies.",
                related_name="movies",
                to="movieWebsite.actor",
            ),
        ),
    ]
